languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "James Stewart"
links = [ { github = "https://github.com/jcstewart13" }, { youtube = "https://youtube.com/@megahertz13" } ]
